// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mysql.Models;

#nullable disable

namespace Mysql.Migrations
{
    [DbContext(typeof(demoContext))]
    partial class demoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Mysql.Models.Dept", b =>
                {
                    b.Property<int>("Deptno")
                        .HasColumnType("int")
                        .HasColumnName("deptno");

                    b.Property<string>("Dname")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("dname");

                    b.Property<string>("Loc")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("loc");

                    b.HasKey("Deptno")
                        .HasName("PRIMARY");

                    b.ToTable("dept", (string)null);
                });

            modelBuilder.Entity("Mysql.Models.Emp", b =>
                {
                    b.Property<int>("Empno")
                        .HasColumnType("int")
                        .HasColumnName("empno");

                    b.Property<float?>("Comm")
                        .HasColumnType("float")
                        .HasColumnName("comm");

                    b.Property<int?>("Deptno")
                        .HasColumnType("int")
                        .HasColumnName("deptno");

                    b.Property<string>("Ename")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ename");

                    b.Property<DateTime?>("Hiredate")
                        .HasColumnType("datetime")
                        .HasColumnName("hiredate");

                    b.Property<string>("Job")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("job");

                    b.Property<int?>("Mgr")
                        .HasColumnType("int")
                        .HasColumnName("mgr");

                    b.Property<float?>("Sal")
                        .HasColumnType("float")
                        .HasColumnName("sal");

                    b.HasKey("Empno")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Deptno" }, "emp_fk");

                    b.ToTable("emp", (string)null);
                });

            modelBuilder.Entity("Mysql.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Addresss")
                        .HasMaxLength(130)
                        .HasColumnType("varchar(130)")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Addresss"), "utf8");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Mysql.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Mysql.Models.Emp", b =>
                {
                    b.HasOne("Mysql.Models.Dept", "DeptnoNavigation")
                        .WithMany("Emps")
                        .HasForeignKey("Deptno")
                        .HasConstraintName("emp_fk");

                    b.Navigation("DeptnoNavigation");
                });

            modelBuilder.Entity("Mysql.Models.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
